# syntax=docker/dockerfile:1
FROM php:8.2-apache
# instala recursos adicionais
RUN apt-get update
RUN apt-get install -y sed 
RUN apt-get install -y vim 
RUN apt-get install -y git 
RUN apt-get install -y zlib1g-dev 
RUN apt-get install -y libzip-dev 
RUN apt-get install -y unzip
RUN apt-get install -y curl
RUN apt-get install -y openssl
RUN apt-get install -y libssl-dev
RUN apt-get install -y libxml2-dev
RUN apt-get install -y nano
RUN apt-get install -y iputils-ping
RUN apt-get install -y dnsutils
RUN apt-get install -y telnet
RUN apt-get install -y libpng-dev
RUN apt-get install -y libjpeg-dev
RUN apt-get install -y cron
# Bibliotecas php
RUN docker-php-ext-install zip
RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install mysqli
RUN docker-php-ext-enable pdo_mysql
RUN docker-php-ext-install soap
RUN docker-php-ext-install gd
# instala openssl utilizando um workaround
RUN docker-php-ext-install openssl || true
RUN cp /usr/src/php/ext/openssl/config0.m4 /usr/src/php/ext/openssl/config.m4
RUN docker-php-ext-install openssl
# cria diretorio do document-root
WORKDIR /var/www
VOLUME /var/www
# copia arquivos de configuracao
COPY ./apache2.conf /etc/apache2/apache2.conf
COPY ./000-default.conf /etc/apache2/sites-available/000-default.conf
COPY ./xdebug-enable.sh /usr/local/etc/php/conf.d/xdebug-enable.sh
COPY ./xdebug-disable.sh /usr/local/etc/php/conf.d/xdebug-disable.sh
COPY ./cacert.pem /usr/local/etc/php/cacert.pem

# Adiciona a entrada do cron
#RUN echo "* * * * * cd /var/www/ && /usr/local/bin/php artisan schedule:run >> /var/www/schedule.log 2>&1" | crontab -

# instala o composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php composer-setup.php --install-dir=/usr/local/bin --filename=composer
# habilita o modulo rewrite
RUN a2enmod rewrite
RUN a2enmod headers
RUN pecl install xdebug-3.3.2 && docker-php-ext-enable xdebug
RUN echo "xdebug.mode=off" | tee -a /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini > /dev/null && \
    echo "xdebug.start_with_request=yes" | tee -a /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini > /dev/null && \
    echo "xdebug.client_host=host.docker.internal" | tee -a /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini > /dev/null && \
    echo "xdebug.discover_client_host=0" | tee -a /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini > /dev/null && \
    echo "xdebug.client_port=9004" | tee -a /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini > /dev/null