FROM rabbitmq:3-management

RUN apt-get update \
    && apt-get install -y --no-install-recommends jq \
    && rm -rf /var/lib/apt/lists/*

COPY rabbitmq/entrypoint-merge-definitions.sh /usr/local/bin/entrypoint-merge-definitions.sh
RUN chmod +x /usr/local/bin/entrypoint-merge-definitions.sh

ENTRYPOINT ["/usr/local/bin/entrypoint-merge-definitions.sh"]
CMD ["rabbitmq-server"]
