services:

  petrvs_db_producao:
    image: mysql:8-debian
    build:
      context: .
      dockerfile: Dockerfile-db
    container_name: petrvs_db_producao
    volumes:
      - ../mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: petrvs
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_TCP_PORT: ${DB_PORT}
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2048M

  petrvs_php_producao:
    build: 
      context: .
      dockerfile: Dockerfile-php
      args:
        ELASTIC_APM_ENABLED: ${ELASTIC_APM_ENABLED:-false}
    container_name: petrvs_php_producao
    working_dir: /var/www
    env_file:
      - ../../../back-end/.env
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - petrvs_db_producao
      - petrvs_rabbitmq
    environment:
      - RABBITMQ_HOST=petrvs_rabbitmq
    volumes:
      - ../../../back-end:/var/www
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2048M

  petrvs_rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile-rabbitmq
    image: petrvs-rabbitmq:producao
    container_name: petrvs_rabbitmq
    env_file:
      - ./.env
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      TZ: "America/Bahia"
    volumes:
      - petrvs_rabbitmq_data:/var/lib/rabbitmq
      - ./configuracoes/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ./configuracoes/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M

volumes:
  petrvs_rabbitmq_data:
    name: petrvs_rabbitmq_data_producao

# Sobre resources
# https://docs.docker.com/config/containers/resource_constraints/
