<?php

namespace App\Enums;

enum SituacaoFuncionalEnum
{
    public static function fromCodigo(int $codigo): string
    {
        return match ($codigo) {
            1  => "ATIVO_PERMANENTE",
            2  => "APOSENTADO",
            3  => "CEDIDO/REQUISITADO",
            4  => "NOMEADO_CARGO_COMISSIONADO",
            5  => "SEM_VINCULO",
            6  => "TABELISTA(ESP/EMERG)",
            7  => "NATUREZA_ESPECIAL",
            8  => "ATIVO_EM_OUTRO_ORGAO",
            9  => "REDISTRIBUIDO",
            10 => "ATIVO_TRANSITORIO",
            11 => "EXCEDENTE_A_LOTACAO",
            12 => "CONTRATO_TEMPORARIO",
            13 => "EM_DISPONIBILIDADE",
            14 => "REQUISITADO_DE_OUTROS_ORGAOS",
            15 => "INSTITUIDOR_PENSAO",
            16 => "REQUISITADO_MILITAR_FORCAS_ARMADAS",
            17 => "APOSENTADO_TCU733/94",
            18 => "EXERCICIO_DESCENTRALIZADO_CARREIRA",
            19 => "EXERCICIO_PROVISORIO",
            20 => "CELETISTA",
            21 => "ATIVO_PERMANENTE_LEI_8878/94",
            22 => "ANISTIADO_ADCT_CF",
            23 => "CELETISTA/EMPREGADO",
            25 => "CLT_ANS_DECISAO_JUDICIAL",
            27 => "CLT_ANS_JUDICIAL_CEDIDO",
            29 => "CLT_APOS_COMPLEMENTO",
            30 => "CLT_APOS_DECISAO_JUDICIAL",
            31 => "INST_PS_DECISAO_JUDICIAL",
            32 => "EMPREGO_PUBLICO",
            33 => "REFORMA_CBM/PM",
            34 => "RESERVA_CBM/PM",
            35 => "REQUISITADO_MILITAR_GDF",
            36 => "ANISTIADO_PUBLICO_L10559",
            37 => "ANISTIADO_PRIVADO_L10559",
            38 => "ATIVO_DECISAO_JUDICIAL",
            40 => "CONTRATO_TEMPORARIO",
            41 => "COLAB_PCCTAE_E_MAGISTERIO",
            42 => "COLABORADOR_ICT",
            43 => "CLT_ANS_DEC_6657/08",
            44 => "EXERCICIO_7_ART93_8112",
            45 => "CEDIDO_SUS/LEI_8270",
            46 => "INST_ANIST_PUBLICO",
            47 => "INST_ANIST_PRIVADO",
            48 => "CELETISTA_DECISAO_JUDICIAL",
            49 => "CONTRATO_TEMPORARIO_CLT",
            50 => "EMPREGO_PCC/EX-TERRITORIO",
            51 => "EXC_INDISCIPLINA",
            52 => "CONTRATO_PROFESSOR_SUBSTITUTO",
            66 => "ESTAGIARIO",
            70 => "ESTAGIARIO_SIGEPE",
            71 => "RESIDENCIA_E_PMM",
            72 => "APOSENTADO_TEMPORARIRIO",
            75 => "CEDIDO_DF_ESTADO_MUNICIPIO",
            76 => "CONTRATO_TEMPORARIO",
            77 => "EXERC_DESCEN_CDT",
            80 => "EXERC_LEI_13681/18",
            84 => "PENSIONISTA",
            93 => "BENEFICIARIO_PENSAO",
            96 => "QE/MRE_CEDIDO",
            97 => "QUADRO_ESPEC_QE/MRE",
            default => 'DESCONHECIDO',
        };
    }
}
